spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/my-blog
    username: h2
    #Set database password from your system env var
    password: ${BLOG_H2_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
logging:
  level:
    root: info
server:
  port: 8084
my:
  blog:
    markdown-file:
      dir: ${user.home}/markdown
    admin:
      user: admin
      password: ${ADMIN_PASSWORD}
    cross-origin: http://localhost:8443,http://localhost:3000,http://localhost:80,http://localhost:433,http://localhost:455,https://explore.zhuqigong.xyz
    jwt:
      secret: $avverAtyv0fg7algTgaXae
      expired-milliseconds: 43200000